"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("reflect-metadata");
const inversify_1 = require("inversify");
const types_1 = require("./types");
const bot_1 = require("./bot");
const finder_ping_1 = require("./services/finder-ping");
const message_responder_1 = require("./services/message-responder");
const discord_js_1 = require("discord.js");
const hello_responder_1 = require("./services/hello-responder");
const hello_message_1 = require("./services/hello-message");
let container = new inversify_1.Container();
container.bind(types_1.TYPES.Bot).to(bot_1.Bot).inSingletonScope();
container.bind(types_1.TYPES.Client).toConstantValue(new discord_js_1.Client());
container.bind(types_1.TYPES.Token).toConstantValue(process.env.TOKEN);
container.bind(types_1.TYPES.MessageResponder).to(message_responder_1.MessageResponder).inSingletonScope();
container.bind(types_1.TYPES.HelloResponder).to(hello_responder_1.HelloResponder).inSingletonScope();
container.bind(types_1.TYPES.HelloMessage).to(hello_message_1.HelloMessage).inSingletonScope();
container.bind(types_1.TYPES.PingFinder).to(finder_ping_1.PingFinder).inSingletonScope();
exports.default = container;
//# sourceMappingURL=inversify.config.js.map